"""
Manually calibrated pixel positions for each world.
Generated by calibration_tool.py

Task: Pick and place with obstacles
- object_to_pickup: The object to move (red marker in visualization)
- obstacle_1, obstacle_2: Clutter objects on table (blue, yellow markers)
- gripper_start: Where gripper begins (white marker)
- target_zone: Where to place the object (green marker)

All positions are in 224×224 pixel coordinates.
"""

from typing import Dict, Tuple

MANUAL_CALIBRATIONS = {
    1: {
        'object_to_pickup': (98, 125),
        'obstacle_1': (129, 103),
        'obstacle_2': (107, 101),
        'gripper_start': (113, 161),
        'target_zone': (62, 154),
    },

    2: {
        'object_to_pickup': (122, 127),
        'obstacle_1': (126, 111),
        'obstacle_2': (108, 110),
        'gripper_start': (139, 123),
        'target_zone': (94, 174),
    },

    3: {
        'object_to_pickup': (104, 155),
        'obstacle_1': (114, 134),
        'obstacle_2': (136, 140),
        'gripper_start': (131, 162),
        'target_zone': (85, 173),
    },

}

def get_manual_positions(world_id: int) -> Dict[str, Tuple[int, int]]:
    """Get manually calibrated positions for a world."""
    if world_id not in MANUAL_CALIBRATIONS:
        raise ValueError(f"No calibration for world {world_id}. Available: {list(MANUAL_CALIBRATIONS.keys())}")
    return MANUAL_CALIBRATIONS[world_id]
